version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    container_name: kitaclick_backend
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - mysql
      - redis
    networks:
      - kitaclick_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    container_name: kitaclick_frontend
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - kitaclick_net

  nginx:
    image: nginx:stable
    container_name: kitaclick_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/kitaclick.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - kitaclick_net

  mysql:
    image: mysql:8.0
    container_name: kitaclick_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kitaclick
      MYSQL_USER: kitaclick
      MYSQL_PASSWORD: strong_db_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - kitaclick_net

  redis:
    image: redis:7-alpine
    container_name: kitaclick_redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - kitaclick_net

volumes:
  mysql-data:
  redis-data:

networks:
  kitaclick_net:
    driver: bridge
