version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  backend:
    build: ./backend
    container_name: kitaclick-backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/var/www/html
    restart: always

  frontend:
    build: ./frontend
    container_name: kitaclick-frontend
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: kitaclick
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
